// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAApAwKhG5RP_qRmBep3MJkATddAb4i1a0',
    appId: '1:907648361280:web:1ca62e697b9929e27410a5',
    messagingSenderId: '907648361280',
    projectId: 'khadamat-app-946b3',
    authDomain: 'khadamat-app-946b3.firebaseapp.com',
    storageBucket: 'khadamat-app-946b3.appspot.com',
    measurementId: 'G-5ZM2X7R8S1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxyRFiwvm8KbEyd_VauWqlEDt_dRSS5cg',
    appId: '1:907648361280:android:fc38eea07affc7687410a5',
    messagingSenderId: '907648361280',
    projectId: 'khadamat-app-946b3',
    storageBucket: 'khadamat-app-946b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwraCCR5k2wahKNGYdS73gUtZ2p-wyuPM',
    appId: '1:907648361280:ios:f0e901474f73d88a7410a5',
    messagingSenderId: '907648361280',
    projectId: 'khadamat-app-946b3',
    storageBucket: 'khadamat-app-946b3.appspot.com',
    iosClientId: '907648361280-28jvvl8c79r4ndnj79e658omtuquojhi.apps.googleusercontent.com',
    iosBundleId: 'com.example.khadamat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwraCCR5k2wahKNGYdS73gUtZ2p-wyuPM',
    appId: '1:907648361280:ios:678e43f32bd724c87410a5',
    messagingSenderId: '907648361280',
    projectId: 'khadamat-app-946b3',
    storageBucket: 'khadamat-app-946b3.appspot.com',
    iosClientId: '907648361280-egiihauklro0n9i4sn4kegjrs4mrkkvg.apps.googleusercontent.com',
    iosBundleId: 'com.example.khadamat.RunnerTests',
  );
}
